[workspace]
members = ["crates/hlight", "crates/hlight-assets", "crates/hlight-dump"]
resolver = "3"

[profile.release]
panic = "unwind"

[profile.thin]
inherits = "release"
panic = "abort"
strip = true
lto = "thin"
opt-level = "s"

[profile.fat]
inherits = "thin"
lto = "fat"
opt-level = "z"

[workspace.package]
rust-version = "1.85.0"
edition = "2024"
authors = ["Moe <m@tmoe.me>"]
license = "Apache-2.0"
repository = "https://github.com/2moe/hlight"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(__unstable_doc)'] }

[workspace.dependencies.syntect]
version = "5.2"
default-features = false

[workspace.dependencies]
getset = "0.1"
log = "0.4"
tap = "1.0"
compact_str = "0.9"
hlight-assets = { path = "crates/hlight-assets" }
# --------------
[package]
name = "tests"
edition.workspace = true

[dev-dependencies]
tap.workspace = true
# thiserror = "2.0"
itertools = "0.14"
# cargo_metadata = "0.19"
hlight = { path = "./crates/hlight" }
anyhow = "1.0.97"
[dev-dependencies.testutils]
version = "0.0.4"
# path = "../testutils"
# --------------
