[alias]
ta = [
    "test",
    "--package",
    "tests",
    "--test",
    "test_all",
    "--all-features",
    "--",
    "test_all",
    "--exact",
    "--show-output",
    "--ignored",
]
open-doc = [
    "test",
    "--package",
    "tests",
    "--test",
    "doc",
    "--all-features",
    "--",
    "build_and_open_rust_doc",
    "--exact",
    "--show-output",
    "--ignored",
]
