[package]
name = "hlight"
version = "0.0.7"
edition.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
exclude = ["/rust-toolchain.toml"]
keywords = ["syntax", "highlighting"]
categories = ["text-processing"]
readme = "Readme.md"
description = "This library is dedicated to delivering exceptional syntax highlighting capabilities."

[features]
default = ["preset-syntax-set", "preset-theme-set"]
preset-syntax-set = ["hlight-assets/syntax-set"]
preset-theme-set = ["hlight-assets/theme-set"]

[dependencies]
getset.workspace = true
log.workspace = true
tap.workspace = true
compact_str.workspace = true
hlight-assets = { workspace = true, optional = true }

[dependencies.syntect]
# version = "5.2"
# default-features = false
features = ["parsing", "regex-fancy"]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "__unstable_doc"]

[lints]
workspace = true
