[package]
name = "hlight"
version = "0.0.4"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
exclude.workspace = true

keywords = ["syntax", "highlighting"]
categories = ["text-processing"]
readme = "Readme.md"
description = "This library is dedicated to delivering exceptional syntax highlighting capabilities."

[features]
default = ["preset-syntax-set", "preset-theme-set"]
preset-syntax-set = []
preset-theme-set = []

[dependencies]
getset.workspace = true
log = { workspace = true }
tap = { workspace = true }
compact_str = { workspace = true }

[dependencies.syntect]
workspace = true
features = ["parsing", "regex-fancy"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "__unstable_doc"]
# targets = ["x86_64-unknown-linux-gnu"]

[lints]
workspace = true
